# Generated by Django 3.0.5 on 2026-02-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0007_clientposts_model_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(default='unknown', max_length=300)),
                ('ratio', models.CharField(default='unknown', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(default='unknown', max_length=300)),
                ('ratio', models.CharField(default='unknown', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='predict_investor_sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Investor_Age', models.CharField(default='unknown', max_length=300)),
                ('Investor_Gender', models.CharField(default='unknown', max_length=300)),
                ('PDate', models.CharField(default='unknown', max_length=300)),
                ('Stock_Text', models.CharField(default='unknown', max_length=30000)),
                ('Stock_Name', models.CharField(default='unknown', max_length=300)),
                ('Company_Name', models.CharField(default='unknown', max_length=300)),
                ('Prediction', models.CharField(default='unknown', max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientposts_model',
            name='userId',
        ),
        migrations.DeleteModel(
            name='review_Model',
        ),
        migrations.AddField(
            model_name='clientregister_model',
            name='address',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='clientregister_model',
            name='gender',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='city',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='country',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='email',
            field=models.EmailField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='password',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='phoneno',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='state',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientregister_model',
            name='username',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.DeleteModel(
            name='ClientPosts_Model',
        ),
    ]
